// SPDX-License-Identifier: BSD-2-Clause
// Authors: Siddhartha Srinivasa and contributors to TSR
//
// A JSON reader for the conformance corpus, and nothing more.
//
// Test-only, and deliberately not a dependency: the library is standard library only, so
// the tests are too, and pulling a JSON library in for one file would put it in every
// consumer's build. The corpus is machine-generated by tools/tsr_conformance.py with
// `json.dumps(indent=1, sort_keys=True)`, so this handles exactly that subset -- objects,
// arrays, strings without escapes, numbers, booleans -- and *throws* on anything else
// rather than guessing. A corpus this cannot read is a corpus the test must not silently
// skip.
#pragma once

#include <cstdlib>
#include <fstream>
#include <map>
#include <memory>
#include <sstream>
#include <stdexcept>
#include <string>
#include <variant>
#include <vector>

namespace testjson {

class Value;
using Object = std::map<std::string, Value>;
using Array = std::vector<Value>;

class Value {
 public:
  using Storage = std::variant<std::monostate, bool, double, std::string, Array, Object>;

  Value() = default;
  explicit Value(Storage v) : v_(std::move(v)) {}

  bool is_null() const { return std::holds_alternative<std::monostate>(v_); }
  bool is_number() const { return std::holds_alternative<double>(v_); }
  bool is_bool() const { return std::holds_alternative<bool>(v_); }

  double number() const { return get<double>("number"); }
  bool boolean() const { return get<bool>("bool"); }
  const std::string& string() const { return get<std::string>("string"); }
  const Array& array() const { return get<Array>("array"); }
  const Object& object() const { return get<Object>("object"); }

  // Keyed lookup that names the missing key: a corpus that grew a field should fail
  // legibly, not with a bad_variant_access from three frames down.
  const Value& operator[](const std::string& key) const {
    const Object& o = object();
    auto it = o.find(key);
    if (it == o.end()) throw std::runtime_error("conformance corpus has no key '" + key + "'");
    return it->second;
  }

  const Value& operator[](std::size_t i) const {
    const Array& a = array();
    if (i >= a.size()) throw std::runtime_error("conformance corpus array index out of range");
    return a[i];
  }

 private:
  template <typename T>
  const T& get(const char* what) const {
    if (const T* p = std::get_if<T>(&v_)) return *p;
    throw std::runtime_error(std::string("conformance corpus value is not a ") + what);
  }

  Storage v_{};
};

namespace detail {

struct Parser {
  const std::string& text;
  std::size_t i = 0;

  void skip() {
    while (i < text.size() && (text[i] == ' ' || text[i] == '\n' || text[i] == '\t' || text[i] == '\r')) ++i;
  }

  [[noreturn]] void bad(const std::string& why) const {
    throw std::runtime_error("conformance corpus is not readable at byte " + std::to_string(i) + ": " + why);
  }

  void expect(char c) {
    skip();
    if (i >= text.size() || text[i] != c) bad(std::string("expected '") + c + "'");
    ++i;
  }

  bool literal(const char* word) {
    const std::size_t n = std::string(word).size();
    if (text.compare(i, n, word) != 0) return false;
    i += n;
    return true;
  }

  std::string parse_string() {
    expect('"');
    std::string out;
    while (true) {
      if (i >= text.size()) bad("unterminated string");
      const char c = text[i++];
      if (c == '"') return out;
      if (c != '\\') {
        out.push_back(c);
        continue;
      }
      if (i >= text.size()) bad("unterminated escape");
      switch (text[i++]) {
        case '"': out.push_back('"'); break;
        case '\\': out.push_back('\\'); break;
        case '/': out.push_back('/'); break;
        case 'b': out.push_back('\b'); break;
        case 'f': out.push_back('\f'); break;
        case 'n': out.push_back('\n'); break;
        case 'r': out.push_back('\r'); break;
        case 't': out.push_back('\t'); break;
        // \u is outside the subset the generator emits. Refuse rather than mangle it.
        default: bad("unsupported string escape");
      }
    }
  }

  Value parse_value() {
    skip();
    if (i >= text.size()) bad("unexpected end of input");
    const char c = text[i];
    if (c == '{') {
      ++i;
      Object o;
      skip();
      if (i < text.size() && text[i] == '}') {
        ++i;
        return Value(Value::Storage(std::move(o)));
      }
      while (true) {
        skip();
        std::string key = parse_string();
        expect(':');
        o.emplace(std::move(key), parse_value());
        skip();
        if (i < text.size() && text[i] == ',') {
          ++i;
          continue;
        }
        expect('}');
        return Value(Value::Storage(std::move(o)));
      }
    }
    if (c == '[') {
      ++i;
      Array a;
      skip();
      if (i < text.size() && text[i] == ']') {
        ++i;
        return Value(Value::Storage(std::move(a)));
      }
      while (true) {
        a.push_back(parse_value());
        skip();
        if (i < text.size() && text[i] == ',') {
          ++i;
          continue;
        }
        expect(']');
        return Value(Value::Storage(std::move(a)));
      }
    }
    if (c == '"') return Value(Value::Storage(parse_string()));
    if (literal("true")) return Value(Value::Storage(true));
    if (literal("false")) return Value(Value::Storage(false));
    if (literal("null")) return Value(Value::Storage(std::monostate{}));

    const char* begin = text.c_str() + i;
    char* end = nullptr;
    const double d = std::strtod(begin, &end);
    if (end == begin) bad("expected a value");
    i += static_cast<std::size_t>(end - begin);
    return Value(Value::Storage(d));
  }
};

}  // namespace detail

inline Value parse(const std::string& text) {
  detail::Parser p{text};
  Value v = p.parse_value();
  p.skip();
  if (p.i != text.size()) p.bad("trailing content");
  return v;
}

inline Value parse_file(const std::string& path) {
  std::ifstream in(path, std::ios::binary);
  if (!in) throw std::runtime_error("cannot open the conformance corpus at " + path);
  std::ostringstream buf;
  buf << in.rdbuf();
  return parse(buf.str());
}

}  // namespace testjson
