blank_issues_enabled: false
contact_links:
  - name: Questions and discussion
    url: https://github.com/personalrobotics/robot-code/discussions
    about: Ask questions or discuss design in the umbrella repo.
