name: Drawer Handle Grasp
description: Grasp drawer handle to pull open
task: actuate
subject: gripper
reference: drawer_handle
T_ref_tsr:
- - 1.0
  - 0.0
  - 0.0
  - 0.0
- - 0.0
  - 1.0
  - 0.0
  - 0.0
- - 0.0
  - 0.0
  - 1.0
  - 0.0
- - 0.0
  - 0.0
  - 0.0
  - 1.0
Tw_e:
- - 1.0
  - 0.0
  - 0.0
  - 0.0
- - 0.0
  - 0.0
  - -1.0
  - 0.04
- - 0.0
  - 1.0
  - 0.0
  - 0.0
- - 0.0
  - 0.0
  - 0.0
  - 1.0
Bw:
- - -0.05
  - 0.05
- - 0.0
  - 0.0
- - 0.0
  - 0.0
- - 0.0
  - 0.0
- - -0.17453292519943295
  - 0.17453292519943295
- - 0.0
  - 0.0
preshape:
- 0.03
