name: Valve Wheel Grasp
description: Grasp valve wheel rim for turning
task: actuate
subject: gripper
reference: valve_wheel
T_ref_tsr:
- - 1.0
  - 0.0
  - 0.0
  - 0.0
- - 0.0
  - 1.0
  - 0.0
  - 0.0
- - 0.0
  - 0.0
  - 1.0
  - 0.0
- - 0.0
  - 0.0
  - 0.0
  - 1.0
Tw_e:
- - 1.0
  - 0.0
  - 0.0
  - 0.0
- - 0.0
  - 0.0
  - -1.0
  - 0.11
- - 0.0
  - 1.0
  - 0.0
  - 0.0
- - 0.0
  - 0.0
  - 0.0
  - 1.0
Bw:
- - 0.0
  - 0.0
- - 0.0
  - 0.0
- - 0.0
  - 0.0
- - -0.3490658503988659
  - 0.3490658503988659
- - 0.0
  - 0.0
- - 0.0
  - 0.0
preshape:
- 0.04
