name: Table Wiping Constraint
description: Keep sponge flat on table while wiping
task: constrain
subject: sponge
reference: table
T_ref_tsr:
- - 1.0
  - 0.0
  - 0.0
  - 0.0
- - 0.0
  - 1.0
  - 0.0
  - 0.0
- - 0.0
  - 0.0
  - 1.0
  - 0.0
- - 0.0
  - 0.0
  - 0.0
  - 1.0
Tw_e:
- - 1.0
  - 0.0
  - 0.0
  - 0.0
- - 0.0
  - -1.0
  - 0.0
  - 0.0
- - 0.0
  - 0.0
  - -1.0
  - 0.0
- - 0.0
  - 0.0
  - 0.0
  - 1.0
Bw:
- - -0.3
  - 0.3
- - -0.2
  - 0.2
- - 0.0
  - 0.0
- - 0.0
  - 0.0
- - 0.0
  - 0.0
- - -3.141592653589793
  - 3.141592653589793
